services:

  postgres:
    image: postgres:17
    container_name: postgres-rls
    volumes:
      - ./scripts/init:/docker-entrypoint-initdb.d:ro
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  db-migration-service:
    image: postgres:alpine
    container_name: db-migration-service
    depends_on:
      postgres:
        condition: service_healthy
    env_file: 
      - .env
    volumes:
      - ./scripts/migrations:/migrations:ro
    entrypoint: ["psql"]
    command:
      - "--set=ON_ERROR_STOP=1"
      - "--host=postgres"
      - "--port=5432"
      - "--username=dbo"
      - "--dbname=demo_db"
      - "--file=/migrations/01_30092026_migrations.sql"
    environment:
      PGPASSWORD: "${POSTGRES_PASSWORD}"
    restart: no

  
volumes:
  data: